### ISSUE TITLE
fix linkArr based parsers

### ISSUE THREAD

**Issue by theSoberSobber** [theSoberSobber/AlertBot#13]
before linkArr didn't exist, so updates with multiple links were impossible
now that linkArr has been added to data json interface, some parsers can be fixed.
nsutParser and iiitbhParser are good and easy.

**Comment by ota0912** [comment]
Modified all parsers to correctly update their respective linkArr attribute for each alert.
Refer to [this commit](
https://github.com/theSoberSobber/AlertBot/commit/e976cea60d96ebe5cba5698c9adfdbefc72f87f8)
