### ISSUE TITLE
"possible mutex deadlock"

### ISSUE THREAD

**Issue by theSoberSobber** [theSoberSobber/AlertBot#14]
i think a deadlock is occuring cus the bot tries to spam in all groups as soon as an update is available.
i think this is the reason for stale session on groups too.
maybe we need some kind of wait before trying second.
look into that.
some issues for refrence, tho not very helpful
https://github.com/adiwajshing/Baileys/issues/2386
btw this is getting logged due to pino : {logger : error} level, making it silent should help make the terminal more clean and sane

**Comment by theSoberSobber** [comment]
ota0912 orz 🛐

**Comment by theSoberSobber** [comment]
https://github.com/adiwajshing/Baileys/issues/2553
more refrence

**Comment by ota0912** [comment]
After thorough consideration and discussion, the need for the issue has been revoked and hence is being closed permanently until any further discrepancies arise!
