### ISSUE TITLE
implement a store

### ISSUE THREAD

**Issue by theSoberSobber** [theSoberSobber/AlertBot#8]
implement a store to fix the waiting for message issue

quoting
`
/**
     * fetch a message from your store
     * implement this so that messages failed to send (solves the "this message can take a while" issue) can be retried
     * */
    getMessage: (key: proto.IMessageKey) => Promise<proto.IMessage | undefined>
`
    
from https://adiwajshing.github.io/Baileys/
also refrence
https://github.com/adiwajshing/Baileys/issues/1555

**Comment by KorigamiK** [comment]
Refer https://github.com/adiwajshing/Baileys/issues/1601

**Comment by ota0912** [comment]
Corrected the interaction functions to return the default sendMessage value
Implemented a tempStore to store message keys.
Refer to [this commit](https://github.com/theSoberSobber/AlertBot/commit/57ee66a843584190f68cdddd50a4d83807c143b3)
